const appname = "hMart";
const appversion = "Version 1.0.0";
const credits = "@HussnulMaab192";
const email = "Email";
const emailHint = "abc@example.com";
const password = "Password";
const passwordHint = "********";
const forgetPassword = "Forgot Password";
const login = "Log in";
const signUp = "Sign up";
const loginWith = "Log in with";
const createNewAccount = "or,Create New Account ?";
const name = "Name";
const nameHint = "Ibad Ur Rehman";
const retypePassword = "Retye Password";
const myprivacyPolicy = "Privacy Policy";
const termsConditions = "Terms & Conditions";
const alreadyHaveAnAccount = "Already Have An Account? ";
const home = "Home";
const category = "Categories";
const cart = "Cart";
const account = "Account";
const searchAnything = "Search Anything...";
const todayDeal = "Today Deal";
const flashSale = "Flash Sale";
const topBrand = "Top Brand";
const topCategories = "Top Categories";
const brands = "Brands";
const topSellers = "Top Sellers";
const featuredCategories = "Featured Categories";
const womenDress = "Women Dress";
const girlsWatches = "Girls Watches";
const mobilePhones = "Mobile Phones";
const boysGlasses = "Boys Glasses ";
const tShirts = "T Shirts";
const girlsDresses = "Girls Dresses";
const featureProduct = "Feature Product";

//  Category String
const womenClothing = "Women Clothing";
const menClothingFashion = "Men Clothing";
const compAccess = "Computer Accessories";
const autoMobile = "Auto Mobiles";
const kidtoys = "Kid Toys";
const sports = "Sports";
const cosmetics = "Cosmetics";
const cellphones = "Cell Phones";
const furniture = "Furniture";
const drillingMachine = "Drilling Machine";

// Item Details Strings

const video = "Video";
const reviews = "Reviews";
const sellerPolicy = "Seller Policy";
const privacyPolicy = "Privacy Policy";
const returnPolicy = "Return Policy";
const supportPolicy = "Support Policy";
const productYouMayAlsoLike = "Products You May Also Like";
